export default {
  AUTH: 'AUTH',
  AUTH_RESET: 'AUTH_RESET',
  GLOBAL: 'GLOBAL',
  GLOBAL_RESET: 'GLOBAL_RESET',
  PUT_USER: 'PUT_USER',

  ACTIVE_CONTACT: 'ACTIVE_CONTACT',
  REMOVE_CONTACT: 'REMOVE_CONTACT',

  SET_AUTH_ERROR: 'SET_AUTH_ERROR',
  REMOVE_AUTH_ERROR: 'REMOVE_AUTH_ERROR',
  SET_AUTH_INFO:'SET_AUTH_INFO',
  REMOVE_AUTH_MSG:'REMOVE_AUTH_MSG',

  GET_STATIC_DATA: 'GET_STATIC_DATA',

  FETCH_ADMINS: 'FETCH_ADMINS',
  ADD_ADMIN: 'ADD_ADMIN',
  UPDATE_ADMIN: 'UPDATE_ADMIN',
  CHANGE_ADMIN_STATUS: 'CHANGE_ADMIN_STATUS',

  FETCH_USERS: 'FETCH_USERS',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  CHANGE_USER_STATUS: 'CHANGE_USER_STATUS'
};
