export default {
  AUTH: 'AUTH',
  AUTH_RESET: 'AUTH_RESET',
  GLOBAL: 'GLOBAL',
  GLOBAL_RESET: 'GLOBAL_RESET',
  PUT_USER: 'PUT_USER',

  ACTIVE_CONTACT: 'ACTIVE_CONTACT',
  REMOVE_CONTACT: 'REMOVE_CONTACT',

  SET_AUTH_ERROR: 'SET_AUTH_ERROR',
  REMOVE_AUTH_ERROR: 'REMOVE_AUTH_ERROR',
  SET_AUTH_INFO:'SET_AUTH_INFO',
  REMOVE_AUTH_MSG:'REMOVE_AUTH_MSG',

  GET_STATIC_DATA: 'GET_STATIC_DATA',

  GET_COURSES: 'GET_COURSES',
  GET_VIDEOS: 'GET_VIDEOS',
  GET_CURRENT_VIDEO: 'GET_CURRENT_VIDEO',

  FETCH_ENROLLMENT: 'FETCH_ENROLLMENT',
  FETCH_ENROLLED_COURSES: 'FETCH_ENROLLED_COURSES'
};
